version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: payment-ecommerce-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payment
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - redelocal

networks:
  redelocal:

volumes:
  postgres-data: